### PR TITLE
quick fix for already-ended streams

### LINKED ISSUE #28: Call callback immediately if stream is already closed.
I'm reviewing this package briefly, and it looks to me like it will hang forever if a closed stream is passed to it, which could happen in a race condition.

### PR DESCRIPTION
**Pull request by xloem**
This is a naive attempt for something that fixes #28

### CODE REVIEW

**Comment by xloem** [comment]
Travis e-mailed me.  I see you're intending to support down to nodejs 4.  This fix only passed my test on nodejs 8 and above.  I don't know how to detect whether a stream has ended on nodejs 4.

**Comment by mafintosh** [comment]
Streams can be many versions due to readable-stream existing so we support a vast majority of them. This a non trivial problem.

What's your real life use-case for this?

**Comment by xloem** [comment]
I'm trying to robustly pull the next item from a stream and throw an error if there is none.  https://npmjs.com/package/stream-shift-promise (as part of a library and tool that uses streams a lot).

I'm not personally worried about versions of npm no longer generally distributed, but I was kind of hoping if I could find another project to merge the idea into it might get better maintenance down the road, with more users.

**Comment by xloem** [comment]
I'm trying to make a tool for probing forms of blockchain data.  It seemed it would be nice to use streams under the hood, since the size range of stuff can vary from miniscule to humongous.  I was running into a lot of issues connecting streams together so I started working on libraries.

**Comment by mafintosh** [comment]
Yea this module got *massive* usage in the ecosystem so we gonna have to test a wide variety of streams to not break stuff. I think any change made to here in the last 12-24 months has caused breakage hehe.

The reason I'm asking about a use case is that I don't think I've had the need to listen for stream end some time after making the stream instance. You gotta error handle it right away anyway. I normally check using stream.destroyed if a stream has error if I need to check that.

**Comment by xloem** [comment]
I don't quite understand you.  I am trying to use streams to hold all of one value, huge values, and no values, so setting up error handlers would be encapsulated inside something.  It sounds like this is not the place, or maybe streams not the tool.  Thank byou.

**Pull request closed without merging**
